// Package scaffold implements the `gforge scaffold` command.
// It reads a .feature file, extracts the bounded context name from the Feature
// title, and generates a hexagonal directory skeleton:
//
//	<out>/
//	  domain/       — aggregate root + ports
//	  usecases/     — use-case orchestrator stub
//	  adapters/
//	    inmemory/   — in-memory adapter stub
//	tests/
//	  fakes/        — fake stubs for each port
//	  godog_test.go — suite initializer wired to the feature file
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
	"unicode"

	"github.com/cucumber/gherkin/go/v26"
	"github.com/spf13/cobra"
)

// NewCommand returns the cobra command for `gforge scaffold`.
func NewCommand() *cobra.Command {
	var featurePath string
	var outDir string

	cmd := &cobra.Command{
		Use:   "scaffold",
		Short: "Generate hexagonal Go skeleton from a .feature file",
		Long: `scaffold reads the given @business feature file and emits:
  - domain aggregate + ports
  - use-case orchestrator stub
  - in-memory adapter stub
  - hand-written fake stubs
  - godog suite initializer`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return run(featurePath, outDir, cmd.OutOrStdout())
		},
	}

	cmd.Flags().StringVar(&featurePath, "feature", "", "path to the @business .feature file (required)")
	cmd.Flags().StringVar(&outDir, "out", ".", "output directory for the generated skeleton")
	_ = cmd.MarkFlagRequired("feature")

	return cmd
}

func run(featurePath, outDir string, stdout interface{ Write([]byte) (int, error) }) error {
	f, err := os.Open(featurePath)
	if err != nil {
		return fmt.Errorf("opening feature file: %w", err)
	}
	defer f.Close()

	var idSeq int
	newIDFunc := func() string { idSeq++; return strconv.Itoa(idSeq) }
	doc, err := gherkin.ParseGherkinDocument(f, newIDFunc)
	if err != nil {
		return fmt.Errorf("parsing feature file: %w", err)
	}
	if doc.Feature == nil {
		return fmt.Errorf("feature file has no Feature block")
	}

	ctx := buildContext(doc.Feature.Name)
	return generate(ctx, outDir, stdout)
}

// scaffoldContext carries template data derived from the feature title.
type scaffoldContext struct {
	Name      string // e.g. "Order"
	NameLower string // e.g. "order"
	NameSnake string // e.g. "order_management"
	Module    string // always github.com/spannersync/gherkinforge for the pilot
}

func buildContext(featureTitle string) scaffoldContext {
	// Take the first word of the feature title as the context name.
	words := strings.Fields(featureTitle)
	name := "Context"
	if len(words) > 0 {
		name = toTitle(words[0])
	}
	return scaffoldContext{
		Name:      name,
		NameLower: strings.ToLower(name),
		NameSnake: toSnake(featureTitle),
		Module:    "github.com/spannersync/gherkinforge",
	}
}

func toTitle(s string) string {
	if len(s) == 0 {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func toSnake(s string) string {
	return strings.ToLower(strings.ReplaceAll(strings.TrimSpace(s), " ", "_"))
}

// generate writes files for each template into outDir.
func generate(ctx scaffoldContext, outDir string, stdout interface{ Write([]byte) (int, error) }) error {
	type fileSpec struct {
		relPath string
		tmpl    string
	}

	files := []fileSpec{
		{
			relPath: filepath.Join("domain", ctx.NameLower+".go"),
			tmpl:    domainTmpl,
		},
		{
			relPath: filepath.Join("domain", "ports.go"),
			tmpl:    portsTmpl,
		},
		{
			relPath: filepath.Join("usecases", "create_"+ctx.NameLower+".go"),
			tmpl:    usecaseTmpl,
		},
		{
			relPath: filepath.Join("adapters", "inmemory", "repository.go"),
			tmpl:    adapterTmpl,
		},
	}

	for _, spec := range files {
		target := filepath.Join(outDir, spec.relPath)
		if err := writeTemplate(target, spec.tmpl, ctx); err != nil {
			return err
		}
		fmt.Fprintf(stdout, "  created %s\n", target)
	}
	return nil
}

func writeTemplate(path, tmplText string, ctx scaffoldContext) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating %s: %w", path, err)
	}
	defer f.Close()

	t, err := template.New("").Parse(tmplText)
	if err != nil {
		return fmt.Errorf("parsing template for %s: %w", path, err)
	}
	return t.Execute(f, ctx)
}

// ── Templates ────────────────────────────────────────────────────────────────

const domainTmpl = `package domain

import "time"

// {{.Name}} is the aggregate root generated by gforge scaffold.
type {{.Name}} struct {
	ID         string
	TotalPence int64 // monetary value — never float64
	CreatedAt  time.Time
}
`

const portsTmpl = `package domain

import "context"

// {{.Name}}Repository is the port that infrastructure adapters must implement.
type {{.Name}}Repository interface {
	Save(ctx context.Context, agg {{.Name}}) error
	FindByID(ctx context.Context, id string) ({{.Name}}, error)
}

// EventPublisher is the port for emitting domain events.
type EventPublisher interface {
	Publish(ctx context.Context, eventName string, payload any) error
}
`

const usecaseTmpl = `package usecases

import (
	"context"
	"fmt"

	"{{.Module}}/pkg/context/{{.NameLower}}/domain"
)

// Create{{.Name}}Command carries the intent from the transport layer.
type Create{{.Name}}Command struct {
	ID string
}

// Create{{.Name}}UseCase orchestrates {{.NameLower}} creation.
type Create{{.Name}}UseCase struct {
	repo      domain.{{.Name}}Repository
	publisher domain.EventPublisher
}

// NewCreate{{.Name}}UseCase constructs the use case with required ports.
func NewCreate{{.Name}}UseCase(repo domain.{{.Name}}Repository, publisher domain.EventPublisher) *Create{{.Name}}UseCase {
	return &Create{{.Name}}UseCase{repo: repo, publisher: publisher}
}

// Execute runs the Create{{.Name}} business workflow.
func (uc *Create{{.Name}}UseCase) Execute(ctx context.Context, cmd Create{{.Name}}Command) (domain.{{.Name}}, error) {
	agg := domain.{{.Name}}{ID: cmd.ID}
	if err := uc.repo.Save(ctx, agg); err != nil {
		return domain.{{.Name}}{}, fmt.Errorf("saving {{.NameLower}}: %w", err)
	}
	if err := uc.publisher.Publish(ctx, "{{.NameLower}}.created", agg); err != nil {
		return domain.{{.Name}}{}, fmt.Errorf("publishing event: %w", err)
	}
	return agg, nil
}
`

const adapterTmpl = `package inmemory

import (
	"context"
	"sync"

	"{{.Module}}/pkg/context/{{.NameLower}}/domain"
)

// {{.Name}}Repository is a thread-safe in-memory adapter.
type {{.Name}}Repository struct {
	mu    sync.RWMutex
	store map[string]domain.{{.Name}}
}

// New{{.Name}}Repository returns an empty in-memory store.
func New{{.Name}}Repository() *{{.Name}}Repository {
	return &{{.Name}}Repository{store: make(map[string]domain.{{.Name}})}
}

func (r *{{.Name}}Repository) Save(_ context.Context, agg domain.{{.Name}}) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.store[agg.ID] = agg
	return nil
}

func (r *{{.Name}}Repository) FindByID(_ context.Context, id string) (domain.{{.Name}}, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	a, ok := r.store[id]
	if !ok {
		return domain.{{.Name}}{}, fmt.Errorf("{{.NameLower}} not found")
	}
	return a, nil
}
`
